channel: xkeycloak
orderer:
  domain: xkeycloak.net
  addr: 192.168.100.100
orgs:
  - name: org1
    domain: org1.com
    peers:
      - name: peer0
        addr: 192.168.100.110
      - name: peer1
        addr: 192.168.100.111
    users: 1
  - name: org2
    domain: org2.com
    peers:
      - name: peer0
        addr: 192.168.100.120
      - name: peer1
        addr: 192.168.100.121
    users: 1
  - name: org3
    domain: org3.com
    peers:
      - name: peer0
        addr: 192.168.100.130
      - name: peer1
        addr: 192.168.100.131
    users: 1

